package types

type SECURITY_DESCRIPTOR_CONTROL WORD

const (
	SE_OWNER_DEFAULTED       SECURITY_DESCRIPTOR_CONTROL = 0x0001
	SE_GROUP_DEFAULTED       SECURITY_DESCRIPTOR_CONTROL = 0x0002
	SE_DACL_PRESENT          SECURITY_DESCRIPTOR_CONTROL = 0x0004
	SE_DACL_DEFAULTED        SECURITY_DESCRIPTOR_CONTROL = 0x0008
	SE_SACL_PRESENT          SECURITY_DESCRIPTOR_CONTROL = 0x0010
	SE_SACL_DEFAULTED        SECURITY_DESCRIPTOR_CONTROL = 0x0020
	SE_DACL_AUTO_INHERIT_REQ SECURITY_DESCRIPTOR_CONTROL = 0x0100
	SE_SACL_AUTO_INHERIT_REQ SECURITY_DESCRIPTOR_CONTROL = 0x0200
	SE_DACL_AUTO_INHERITED   SECURITY_DESCRIPTOR_CONTROL = 0x0400
	SE_SACL_AUTO_INHERITED   SECURITY_DESCRIPTOR_CONTROL = 0x0800
	SE_DACL_PROTECTED        SECURITY_DESCRIPTOR_CONTROL = 0x1000
	SE_SACL_PROTECTED        SECURITY_DESCRIPTOR_CONTROL = 0x2000
	SE_RM_CONTROL_VALID      SECURITY_DESCRIPTOR_CONTROL = 0x4000
	SE_SELF_RELATIVE         SECURITY_DESCRIPTOR_CONTROL = 0x8000
)

type PSECURITY_DESCRIPTOR_CONTROL *SECURITY_DESCRIPTOR_CONTROL

// ACL
type ACL struct {
	AclRevision BYTE
	Sbz1        BYTE
	AclSize     WORD
	AceCount    WORD
	Sbz2        WORD
}

type PACL *ACL

type SECURITY_DESCRIPTOR struct {
	Revision BYTE
	Sbz1     BYTE
	Control  SECURITY_DESCRIPTOR_CONTROL
	Owner    PSID
	Group    PSID
	Sacl     PACL
	Dacl     PACL
}

type PSECURITY_DESCRIPTOR *SECURITY_DESCRIPTOR

type SECURITY_ATTRIBUTES struct {
	NLength              DWORD
	LPSecurityDescriptor PSECURITY_DESCRIPTOR
	BInheritHandle       BOOL
}

type LPSECURITY_ATTRIBUTES *SECURITY_ATTRIBUTES
