//go:build windows
// +build windows

package advapi32

import (
	"golang.org/x/sys/windows"
)

var (
	dll = windows.NewLazyDLL("advapi32.dll")

	// winreg.h
	procAbortSystemShutdown         = dll.NewProc("AbortSystemShutdownW")
	procInitiateShutdown            = dll.NewProc("InitiateShutdownW")
	procInitiateSystemShutdown      = dll.NewProc("InitiateSystemShutdownW")
	procInitiateSystemShutdownEx    = dll.NewProc("InitiateSystemShutdownExW")
	procRegCloseKey                 = dll.NewProc("RegCloseKey")
	procRegConnectRegistry          = dll.NewProc("RegConnectRegistryW")
	procRegCopyTree                 = dll.NewProc("RegCopyTreeW")
	procRegCreateKeyEx              = dll.NewProc("RegCreateKeyExW")
	procRegCreateKeyTransacted      = dll.NewProc("RegCreateKeyTransactedW")
	procRegCreateKey                = dll.NewProc("RegCreateKeyW")
	procRegDeleteKeyEx              = dll.NewProc("RegDeleteKeyExW")
	procRegDeleteKeyTransacted      = dll.NewProc("RegDeleteKeyTransactedW")
	procRegDeleteKeyValue           = dll.NewProc("RegDeleteKeyValueW")
	procRegDeleteKey                = dll.NewProc("RegDeleteKeyW")
	procRegDeleteTree               = dll.NewProc("RegDeleteTreeW")
	procRegDeleteValue              = dll.NewProc("RegDeleteValueW")
	procRegDisablePredefinedCache   = dll.NewProc("RegDisablePredefinedCache")
	procRegDisablePredefinedCacheEx = dll.NewProc("RegDisablePredefinedCacheEx")
	procRegDisableReflectionKey     = dll.NewProc("RegDisableReflectionKey")
	procRegEnableReflectionKey      = dll.NewProc("RegEnableReflectionKey")
	procRegEnumKeyEx                = dll.NewProc("RegEnumKeyExW")
	procRegEnumKey                  = dll.NewProc("RegEnumKeyW")
	procRegEnumValue                = dll.NewProc("RegEnumValueW")
	procRegFlushKey                 = dll.NewProc("RegFlushKey")
	procRegGetKeySecurity           = dll.NewProc("RegGetKeySecurity")
	procRegGetValue                 = dll.NewProc("RegGetValueW")
	procRegLoadAppKey               = dll.NewProc("RegLoadAppKeyW")
	procRegLoadKey                  = dll.NewProc("RegLoadKeyW")
	procRegLoadMUIString            = dll.NewProc("RegLoadMUIStringW")
	procRegNotifyChangeKeyValue     = dll.NewProc("RegNotifyChangeKeyValue")
	procRegOpenCurrentUser          = dll.NewProc("RegOpenCurrentUser")
	procRegOpenKeyEx                = dll.NewProc("RegOpenKeyExW")
	procRegOpenKeyTransacted        = dll.NewProc("RegOpenKeyTransactedW")
	procRegOpenKey                  = dll.NewProc("RegOpenKeyW")
	procRegOpenUserClassesRoot      = dll.NewProc("RegOpenUserClassesRoot")
	procRegOverridePredefKey        = dll.NewProc("RegOverridePredefKey")
	procRegQueryInfoKey             = dll.NewProc("RegQueryInfoKeyW")
	procRegQueryMultipleValues      = dll.NewProc("RegQueryMultipleValuesW")
	procRegQueryReflectionKey       = dll.NewProc("RegQueryReflectionKey")
	procRegQueryValueEx             = dll.NewProc("RegQueryValueExW")
	procRegQueryValue               = dll.NewProc("RegQueryValueW")
	procRegRenameKey                = dll.NewProc("RegRenameKey")
	procRegReplaceKey               = dll.NewProc("RegReplaceKeyW")
	procRegRestoreKey               = dll.NewProc("RegRestoreKeyW")
	procRegSaveKeyEx                = dll.NewProc("RegSaveKeyExW")
	procRegSaveKey                  = dll.NewProc("RegSaveKeyW")
	procRegSetKeySecurity           = dll.NewProc("RegSetKeySecurity")
	procRegSetKeyValue              = dll.NewProc("RegSetKeyValueW")
	procRegSetValueEx               = dll.NewProc("RegSetValueExW")
	procRegSetValue                 = dll.NewProc("RegSetValueW")
	procRegUnLoadKey                = dll.NewProc("RegUnLoadKeyW")

	// winsvc.h
	procChangeServiceConfig2             = dll.NewProc("ChangeServiceConfig2W")
	procChangeServiceConfig              = dll.NewProc("ChangeServiceConfigW")
	procCloseServiceHandle               = dll.NewProc("CloseServiceHandle")
	procControlService                   = dll.NewProc("ControlService")
	procControlServiceEx                 = dll.NewProc("ControlServiceExW")
	procCreateService                    = dll.NewProc("CreateServiceW")
	procDeleteService                    = dll.NewProc("DeleteService")
	procEnumDependentServices            = dll.NewProc("EnumDependentServicesW")
	procEnumServicesStatusEx             = dll.NewProc("EnumServicesStatusExW")
	procEnumServicesStatus               = dll.NewProc("EnumServicesStatusW")
	procGetServiceDirectory              = dll.NewProc("GetServiceDirectory")
	procGetServiceDisplayName            = dll.NewProc("GetServiceDisplayNameW")
	procGetServiceKeyName                = dll.NewProc("GetServiceKeyNameW")
	procGetServiceRegistryStateKey       = dll.NewProc("GetServiceRegistryStateKey")
	procGetSharedServiceDirectory        = dll.NewProc("GetSharedServiceDirectory")
	procGetSharedServiceRegistryStateKey = dll.NewProc("GetSharedServiceRegistryStateKey")
	procLockServiceDatabase              = dll.NewProc("LockServiceDatabase")
	procNotifyBootConfigStatus           = dll.NewProc("NotifyBootConfigStatus")
	procNotifyServiceStatusChange        = dll.NewProc("NotifyServiceStatusChangeW")
	procOpenSCManager                    = dll.NewProc("OpenSCManagerW")
	procOpenService                      = dll.NewProc("OpenServiceW")
	procQueryServiceConfig2              = dll.NewProc("QueryServiceConfig2W")
	procQueryServiceConfig               = dll.NewProc("QueryServiceConfigW")
	procQueryServiceDynamicInformation   = dll.NewProc("QueryServiceDynamicInformation")
	procQueryServiceLockStatus           = dll.NewProc("QueryServiceLockStatusW")
	procQueryServiceObjectSecurity       = dll.NewProc("QueryServiceObjectSecurity")
	procQueryServiceStatus               = dll.NewProc("QueryServiceStatus")
	procQueryServiceStatusEx             = dll.NewProc("QueryServiceStatusEx")
	procRegisterServiceCtrlHandler       = dll.NewProc("RegisterServiceCtrlHandlerW")
	procRegisterServiceCtrlHandlerEx     = dll.NewProc("RegisterServiceCtrlHandlerExW")
	procSetServiceObjectSecurity         = dll.NewProc("SetServiceObjectSecurity")
	procSetServiceStatus                 = dll.NewProc("SetServiceStatus")
	procStartService                     = dll.NewProc("StartServiceW")
	procStartServiceCtrlDispatcher       = dll.NewProc("StartServiceCtrlDispatcherW")
	procUnlockServiceDatabase            = dll.NewProc("UnlockServiceDatabase")

	// evntrace.h
	procCloseTrace                 = dll.NewProc("CloseTrace")
	procControlTrace               = dll.NewProc("ControlTraceW")
	procCreateTraceInstanceId      = dll.NewProc("CreateTraceInstanceId")
	procEnableTrace                = dll.NewProc("EnableTrace")
	procEnableTraceEx              = dll.NewProc("EnableTraceEx")
	procEnableTraceEx2             = dll.NewProc("EnableTraceEx2")
	procEnumerateTraceGuids        = dll.NewProc("EnumerateTraceGuids")
	procEnumerateTraceGuidsEx      = dll.NewProc("EnumerateTraceGuidsEx")
	procFlushTrace                 = dll.NewProc("FlushTraceW")
	procGetTraceEnableFlags        = dll.NewProc("GetTraceEnableFlags")
	procGetTraceEnableLevel        = dll.NewProc("GetTraceEnableLevel")
	procGetTraceLoggerHandle       = dll.NewProc("GetTraceLoggerHandle")
	procOpenTrace                  = dll.NewProc("OpenTraceW")
	provProcessTrace               = dll.NewProc("ProcessTrace")
	procQueryAllTraces             = dll.NewProc("QueryAllTracesW")
	procQueryTraceProcessingHandle = dll.NewProc("QueryTraceProcessingHandle")
	procQueryTrace                 = dll.NewProc("QueryTraceW")
	procRegisterTraceGuids         = dll.NewProc("RegisterTraceGuidsW")
	procRemoveTraceCallback        = dll.NewProc("RemoveTraceCallback")
	procSetTraceCallback           = dll.NewProc("SetTraceCallback")
	procStartTrace                 = dll.NewProc("StartTraceW")
	procStopTrace                  = dll.NewProc("StopTraceW")
	procTraceEvent                 = dll.NewProc("TraceEvent")
	procTraceEventInstance         = dll.NewProc("TraceEventInstance")
	procTraceMessage               = dll.NewProc("TraceMessage")
	procTraceMessageVa             = dll.NewProc("TraceMessageVa")
	procTraceQueryInformation      = dll.NewProc("TraceQueryInformation")
	procTraceSetInformation        = dll.NewProc("TraceSetInformation")
	procUnregisterTraceGuids       = dll.NewProc("UnregisterTraceGuids")
	procUpdateTrace                = dll.NewProc("UpdateTraceW")
)
